const swaggerAutogen = require("swagger-autogen")();

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./router.js"];

const doc = {
  info: {
    version: "1.0.0",
    title: "TODO API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  tags: [
    {
      name: "Endpoints",
      description: "Auth and Tasks endpoints",
    },
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header",
    },
  },
  definitions: {
    UserCredentials: {
      email: "email@email.com",
      password: "123@4",
    },
    UserToken: {
      user: { $ref: "#/definitions/User" },
      token:
        "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
    },
    User: {
      id: 1,
      name: "Fulano de Tal",
      email: "email@email.com",
      password: null,
    },
    AddUser: {
      name: "Fulano de Tal",
      email: "email@email.com",
      password: "123@4",
    },
    Users: [{ $ref: "#/definitions/User" }],
    Task: {
      id: "a858e1c3-3dcd-4a93-aebd-4c4131f35e40",
      title: "Lavar o rosto",
      category: "Higiene",
      done: false,
      deadline: "2023-11-15T09:00:00.000",
      userId: "a858e1c3-3dcd-4a93-aebd-4c4131f35e40",
    },
    AddTask: {
      title: "Lavar o rosto",
      category: "Higiene",
      done: false,
      deadline: "2023-11-15T09:00:00.000",
      userId: "a858e1c3-3dcd-4a93-aebd-4c4131f35e40",
    },
    Tasks: [{ $ref: "#/definitions/Task" }],
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./app");
});
